# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-21 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaCuocGoi', models.IntegerField()),
                ('ThoiGian', models.DateTimeField()),
                ('NguoiGoi', models.CharField(max_length=10)),
                ('NguoiNhan', models.CharField(max_length=10)),
                ('TrangThai', models.CharField(max_length=50)),
                ('DoChuong', models.CharField(max_length=10)),
                ('DamThoai', models.CharField(max_length=10)),
                ('ChieuGoi', models.CharField(max_length=20)),
                ('Record', models.CharField(max_length=200)),
                ('NgatMay', models.CharField(max_length=100)),
            ],
        ),
    ]
