# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-21 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='ThoiGian',
            field=models.CharField(max_length=50),
        ),
    ]
