# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-21 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_auto_20230221_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='ChieuGoi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='DamThoai',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='DoChuong',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='NgatMay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='NguoiGoi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='NguoiNhan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='Record',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='ThoiGian',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='TrangThai',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
