# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-22 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20230221_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='DamThoai',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='DoChuong',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='ThoiGian',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
